spring:
  application:
    name: @project.artifactId@
    version: @project.version@
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    baseline-on-migrate: true

server:
  port: 8080
  error:
    include-message: always

rsa:
  private-key: file:${CERTS_PATH:/etc/certs}/private-key.pem
  public-key: file:${CERTS_PATH:/etc/certs}/public-key.pem

logging:
  level:
    org:
      springframework: INFO