spring:
  application:
    name: @project.artifactId@
    version: @project.version@
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-security
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
  error:
    include-message: always

rsa:
  private-key: file:${CERTS_PATH:/etc/certs}/private-key.pem
  public-key: file:${CERTS_PATH:/etc/certs}/public-key.pem

logging:
  level:
    org:
      springframework: INFO