CREATE TABLE if not exists T_USER
(
    id         INT AUTO_INCREMENT,
    username   VARCHAR(255) NOT NULL,

    password   VARCHAR(20)  NOT NULL DEFAULT SUBSTRING(MD5(RAND()) FROM 1 FOR 20),
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    CONSTRAINT UC_UserName UNIQUE (username)
);